version: 2.1

orbs: # Orbs
  gcp-gcr: circleci/gcp-gcr@0.13.0
  github-cli: circleci/github-cli@2.0.0
  node: circleci/node@5.0.0

jobs:
  build_and_push_image:
    machine:
      docker_layer_caching: true # Docker Layer Caching
      resource_class: large # Resource Class(Linux VM)
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: circleci-demo-gitops
          tag: '${CIRCLE_SHA1:0:7}'
          registry-url: asia.gcr.io
      - gcp-gcr/push-image:
          image: circleci-demo-gitops
          tag: '${CIRCLE_SHA1:0:7}'
          registry-url: asia.gcr.io
  
  create_release_pr:
    docker:
      - image: cimg/base:2021.12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - github-cli/setup
      - github-cli/clone:
          repo: git@github.com:tadashi0713/circleci-demo-gitops-manifest.git
      - run:
          name: Edit manifest file using yq
          command: |
            wget -q https://github.com/mikefarah/yq/releases/download/v4.16.2/yq_linux_386
            sudo mv yq_linux_386 /usr/local/bin/yq
            sudo chmod +x /usr/local/bin/yq
            yq e -i '.spec.template.spec.containers[0].image |="asia.gcr.io/'${GOOGLE_PROJECT_ID}'/circleci-demo-gitops:'${CIRCLE_SHA1:0:7}'"' deployment.yaml
      - run:
          name: Commit file
          command: |
            git config --global user.email "gitops@example.com"
            git config --global user.name "GitOps Bot"
            git remote set-url --push origin git@github.com:tadashi0713/circleci-demo-gitops-manifest.git
            git checkout -b release-${CIRCLE_SHA1:0:7}
            git add .
            git commit -m"Release circleci-demo-gitops-app ${CIRCLE_SHA1:0:7}"
            git push origin HEAD
      - run:
          name: Create Pull Request
          command: gh pr create -t "Release circleci-demo-gitops-app ${CIRCLE_SHA1:0:7}" -b ""

workflows:
  test_and_deploy: 
    jobs:
      - node/run:
          name: lint
          npm-run: lint
      - node/run:
          name: build
          npm-run: build
      - build_and_push_image:
          context: push-gcr
          filters:
            branches:
              only: master
      - create_release_pr:
          context:
            - gh-cli
            - push-gcr
          requires:
            - build_and_push_image
