version: 2.1

orbs: # Orbs
  node: circleci/node@5.0.0
  gcp-gcr: circleci/gcp-gcr@0.13.0
  github-cli: circleci/github-cli@2.0.0

jobs:
  build_and_push_image:
    machine:
      docker_layer_caching: true # Docker Layer Caching
      resource_class: large # Resource Class(Linux VM)
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: circleci-demo-gitops
          tag: '${CIRCLE_SHA1}'
          registry-url: asia.gcr.io
      - gcp-gcr/push-image:
          image: circleci-demo-gitops
          tag: '${CIRCLE_SHA1}'
          registry-url: asia.gcr.io
  
  create_release_pr:
    docker:
      - image: cimg/base:2021.12
    steps:
      - github-cli/setup
      - github-cli/clone:
          repo: git@github.com:tadashi0713/circleci-demo-gitops-manifest.git
      - run:
          name: Edit manifest file using yq
          command: |
            snap install yq
            yq -ry '.spec.template.spec.containers[0].image
            |="gcr.io/'${PROJECT_ID}'/'${CONTAINER_NAME}':'${COMMIT_HASH}'"'
            deployment.yml.tmpl > deployment.yml

workflows:
  test_and_deploy: 
    jobs:
      - node/run:
          name: lint
          npm-run: lint
      - build_and_push_image:
          context: push-gcr
          filters:
            branches:
              only: master
      - create_release_pr:
          context: gh-cli
          requires:
            - build_and_push_image
