version: 2.1

orbs: # Orbs
  gcp-cli: circleci/gcp-cli@3.1.1
  github-cli: circleci/github-cli@2.0.0
  node: circleci/node@5.0.0

jobs:
  build_and_push_image:
    machine:
      image: ubuntu-2004:202111-01
      docker_layer_caching: true # Docker Layer Caching
      resource_class: large # Resource Class(Linux VM)
    steps:
      - checkout
      - gcp-cli/setup
      - run:
          name:
          command: |
            gcloud auth configure-docker us-docker.pkg.dev
            docker build ./ -t us-docker.pkg.dev/circleci-tadashi/circleci-demo-release/app
            docker push us-docker.pkg.dev/circleci-tadashi/circleci-demo-release/app

  create_release_pr:
    docker:
      - image: cimg/base:2022.12
    steps:
      - github-cli/setup
      - github-cli/clone:
          repo: git@github.com:tadashi0713/circleci-demo-gitops-manifest.git
      - run:
          name: Edit manifest file using yq
          command: |
            wget -q https://github.com/mikefarah/yq/releases/download/v4.16.2/yq_linux_386
            sudo mv yq_linux_386 /usr/local/bin/yq
            sudo chmod +x /usr/local/bin/yq
            yq e -i '.spec.template.spec.containers[0].image |="asia.gcr.io/'${GOOGLE_PROJECT_ID}'/circleci-demo-gitops:'${CIRCLE_SHA1:0:7}'"' deployment.yaml
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run:
          name: Commit file
          command: |
            git config --global user.email "gitops@example.com"
            git config --global user.name "GitOps Bot"
            git remote set-url --push origin git@github.com:tadashi0713/circleci-demo-gitops-manifest.git
            git checkout -b release-${CIRCLE_SHA1:0:7}
            git add .
            git commit -m"Release circleci-demo-gitops-app ${CIRCLE_SHA1:0:7}"
            git push origin HEAD
      - run:
          name: Create Pull Request
          command: gh pr create -t "Release circleci-demo-gitops-app ${CIRCLE_SHA1:0:7}" -b ""

workflows:
  test_and_deploy: 
    jobs:
      - node/run:
          name: lint
          npm-run: lint
      - node/run:
          name: build
          npm-run: build
      - build_and_push_image:
          context: push-gcr
          filters:
            branches:
              only: master
      # - create_release_pr:
      #     context:
      #       - gh-cli
      #       - push-gcr
      #     requires:
      #       - build_and_push_image
